In [1]:
import sys
sys.path.append('../src')

import numpy as np
import cvxpy as cp
from dbcp import BiconvexProblem

np.random.seed(10015)

In [2]:
A = np.random.randn(10, 20)
X = cp.Variable((10, 5), nonneg=True)
Y = cp.Variable((5, 20), nonneg=True)

obj = cp.Maximize(-cp.sum_squares(X @ Y - A))
constr = [X >= 0, Y >= 0]
X.project_and_assign(np.random.standard_normal(X.shape))
Y.project_and_assign(np.random.standard_normal(Y.shape))
prob = BiconvexProblem(obj, ([X], [Y]), constr)
prob.is_dbcp()

True

In [3]:
prob.solve()

========================= DBCP Summary ==========================
iter    xcost                ycost                gap       
-----------------------------------------------------------------
0       -161.440005584       -142.747821441       18.692184143
1       -138.115816279       -132.491157640       5.624658639
2       -131.535070358       -129.531403569       2.003666789
3       -128.819015219       -127.659566580       1.159448638
4       -127.121441030       -125.869682083       1.251758946
5       -125.282902228       -123.729492512       1.553409716
6       -123.065371747       -121.612779745       1.452592002
7       -120.913386928       -119.663686044       1.249700883
8       -119.062508307       -117.689976349       1.372531958
9       -116.964845358       -115.702903245       1.261942113
10      -115.306754098       -114.436883996       0.869870103
11      -114.106641618       -113.430224603       0.676417015
12      -113.214305723       -112.856832126       0.357473597


np.float64(-112.33598642454234)

In [6]:
prob.status

'converge'

In [5]:
prob._x_prob.status

In [2]:
x = cp.Variable((3, 3), PSD=True)
x.project_and_assign(np.random.randn(3, 3))
y = cp.Variable((3))

A = np.random.normal(size=(3, 3))
b = np.random.normal(3)

obj = cp.Minimize(cp.sum_squares(A @ x @y - b))
constr = [x >= 0]
prob = BiconvexProblem(obj, [[x], [y]], constr)
prob.is_dbcp()

True

In [3]:
x.project_and_assign(np.random.randn(3, 3))


In [4]:
x.value

array([[ 0.72285141,  0.52159561, -0.23934163],
       [ 0.52159561,  0.39395915, -0.24390003],
       [-0.23934163, -0.24390003,  0.36748173]])

In [7]:
prob.x_prob.variables()[0].value

array([[ 0.72285141,  0.52159561, -0.23934163],
       [ 0.52159561,  0.39395915, -0.24390003],
       [-0.23934163, -0.24390003,  0.36748173]])

In [8]:
prob.y_prob.parameters()[0].value

array([[ 0.72285141,  0.52159561, -0.23934163],
       [ 0.52159561,  0.39395915, -0.24390003],
       [-0.23934163, -0.24390003,  0.36748173]])

In [6]:
prob.variables()[0].value

array([[0.33800465, 0.02333135, 0.10654584],
       [0.02333135, 0.00161049, 0.00735451],
       [0.10654584, 0.00735451, 0.03358538]])

In [19]:
v = cp.Variable((3, 3), PSD=True)
v.project_and_assign(np.random.standard_normal(v.shape))
v.value

array([[ 0.61358204, -0.5878544 ,  0.11498293],
       [-0.5878544 ,  0.63049973, -0.18644349],
       [ 0.11498293, -0.18644349,  0.10801716]])

In [40]:
prob = cp.Problem(cp.Minimize(0))

In [41]:
constr = [x == 0]
prob = cp.Problem(cp.Minimize(0), constraints=constr)
prob.constraints

[Equality(Variable((3, 3), var47), Constant(CONSTANT, ZERO, ()))]

In [42]:
prob.constraints[0].args

[Variable((3, 3), var47), Constant(CONSTANT, ZERO, ())]

In [43]:
isinstance(prob.constraints[0], cp.constraints.nonpos.Equality)

AttributeError: module 'cvxpy.constraints.nonpos' has no attribute 'Equality'

In [50]:
x << 0

PSD(Expression(AFFINE, UNKNOWN, (3, 3)))

In [47]:
cp.Zero(x)

Zero(Variable((3, 3), var47))

In [62]:
A = cp.Parameter((3, 3))
b = cp.Parameter(3)
x = cp.Variable(3)
c = cp.Parameter(3)
d = cp.Parameter(1)
t = cp.Constant(3)

cp.SOC((c @ cp.multiply(x, t) + d), A @ cp.multiply(x, t) + b).is_dcp()

True

In [20]:
cp.SOC(b, A, axis=1).shape

ValueError: Argument dimensions () and (3, 3), with axis=1, are incompatible.

In [11]:
x = cp.Variable(1)
p = cp.Problem(cp.Minimize(x), [x >= 0])
p.solve()
p.status

'optimal'

In [12]:
x.project_and_assign(100)

In [16]:
p.solve()

8.189087997509205e-25